version: '3.8'

services:
  # 1. Veritabanı Servisimiz (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: sensorpulse_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # 2. API Servisimiz (FastAPI)
  api:
    build: .
    container_name: sensorpulse_api
    ports:
      - "8000:8000"
    environment:
      # Ağ Programlama Notu: Konteynerler arası iletişimde 'localhost' yerine servis adı olan 'db' kullanılır!
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_API_KEY: ${ADMIN_API_KEY}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: